//! Pointing a coding agent at the local model.
//!
//! [`crate::serve`] puts the checkpoint behind an OpenAI-compatible endpoint. That is only
//! half of it: an agent still has to be told the endpoint exists, and every agent spells that
//! differently. This module writes those files.
//!
//! **Project-local, never global.** Each agent here has a documented per-project config that
//! merges over the user's own — `.zerostack/config.toml`, `opencode.json` — and that is what
//! pstore writes. Editing `~/.config` would reach every checkout on the machine from one
//! project's window, and would put pstore in the business of merging into a file someone else
//! owns. A project file is scoped, obvious, greppable, and deleted with `rm`.
//!
//! **Nothing is overwritten blind.** A file pstore did not write is left alone and reported,
//! not merged and not clobbered. The marker in [`STAMP`] is what tells them apart, so a file
//! pstore wrote last week is refreshed while one you wrote by hand is never touched.

use std::path::{Path, PathBuf};

use crate::serve::Serving;

/// Written into every generated file, and the thing that makes overwriting safe.
///
/// Without a marker the only options are clobbering a file that might be hand-written or
/// refusing to update one pstore itself produced. With it, the two cases separate cleanly.
pub const STAMP: &str = "generated by pstore";

/// Placeholder credential for the local endpoint.
///
/// `llama-server` authenticates nothing unless it is started with `--api-key`, and pstore
/// does not start it that way. But an OpenAI-typed provider with no key configured falls back
/// to `$OPENAI_API_KEY`, and both agents here refuse to start when that is unset — the failure
/// is a credential error for a server that wants no credential. So one is supplied, and it is
/// named to say what it is wherever it surfaces.
pub const LOCAL_KEY: &str = "local-no-key-required";

/// An agent that can be pointed at a local OpenAI-compatible endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Wiring {
    /// Registry id of the agent this configures.
    pub agent_id: &'static str,
    /// What to call it in the UI.
    pub display: &'static str,
    /// Path of the generated file, relative to the project directory.
    pub file: &'static str,
}

/// Every agent pstore knows how to point at the local model.
///
/// Both take a custom OpenAI-compatible provider, which is the only shape a local server can
/// present. Agents whose model list is fixed to a vendor's catalogue cannot be wired up this
/// way at all, and are deliberately absent rather than half-supported.
pub const WIRINGS: &[Wiring] = &[
    Wiring {
        agent_id: "zerostack",
        display: "zerostack",
        file: ".zerostack/config.toml",
    },
    Wiring {
        agent_id: "opencode",
        display: "OpenCode",
        file: "opencode.json",
    },
];

impl Wiring {
    /// The file this would write, for `serving`.
    pub fn path(&self, dir: &Path) -> PathBuf {
        dir.join(self.file)
    }

    /// The exact text pstore would write, so the UI can show it before anything is written.
    ///
    /// Shown rather than described: this drops a file into someone's repository, and "here is
    /// the file" is a better answer to "what will this do?" than any sentence about it.
    pub fn contents(&self, serving: &Serving) -> String {
        let base = serving.base_url();
        let model = serving.model_name();
        let title = serving.title();

        match self.agent_id {
            // `custom_providers` with `provider_type = "openai"` and a `base_url`, which
            // zerostack documents for exactly this case.
            "zerostack" => format!(
                "# {STAMP} — {title}, served locally by pstore.\n\
                 # Delete this file to go back to your usual provider.\n\
                 \n\
                 provider = \"bonsai\"\n\
                 model = \"{model}\"\n\
                 \n\
                 # A placeholder, and it has to be here. The endpoint is a local\n\
                 # llama-server, which authenticates nothing — but an OpenAI-typed provider\n\
                 # with no key resolves to $OPENAI_API_KEY, and zerostack refuses to start\n\
                 # when that is unset. The value is never checked by anything.\n\
                 [api_keys]\n\
                 bonsai = \"{LOCAL_KEY}\"\n\
                 \n\
                 [custom_providers.bonsai]\n\
                 provider_type = \"openai\"\n\
                 base_url = \"{base}\"\n\
                 # Chat Completions rather than the Responses API: llama-server speaks the\n\
                 # former, and `api_style` defaults the right way only some of the time.\n\
                 api_style = \"completions\"\n\
                 model = \"{model}\"\n"
            ),
            // OpenCode reaches a custom endpoint through the AI SDK's openai-compatible
            // provider. The model has to be listed explicitly — the endpoint's own `/v1/models`
            // is not consulted for provider definitions.
            "opencode" => format!(
                "{{\n  \
                   \"$schema\": \"https://opencode.ai/config.json\",\n  \
                   \"_comment\": \"{STAMP} — {title}, served locally by pstore. Delete this \
                   file to go back to your usual provider.\",\n  \
                   \"model\": \"bonsai/{model}\",\n  \
                   \"provider\": {{\n    \
                     \"bonsai\": {{\n      \
                       \"npm\": \"@ai-sdk/openai-compatible\",\n      \
                       \"name\": \"Bonsai (local, via pstore)\",\n      \
                       \"options\": {{ \"baseURL\": \"{base}\", \"apiKey\": \"{LOCAL_KEY}\" }},\n      \
                       \"models\": {{ \"{model}\": {{ \"name\": \"{title}\" }} }}\n    \
                     }}\n  \
                   }}\n\
                 }}\n"
            ),
            _ => String::new(),
        }
    }
}

/// What happened to one agent's config.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Wrote {
    /// The file was created.
    Created(PathBuf),
    /// A file pstore had written before was brought up to date.
    Updated(PathBuf),
    /// It already said the right thing.
    Unchanged(PathBuf),
    /// Someone else's file is there. Left exactly as it was.
    Foreign(PathBuf),
    /// It could not be written, with the reason.
    Failed(String),
}

impl Wrote {
    /// One line for the status bar.
    pub fn label(&self, agent: &str) -> String {
        match self {
            Wrote::Created(p) => format!("{agent}: wrote {}", short(p)),
            Wrote::Updated(p) => format!("{agent}: updated {}", short(p)),
            Wrote::Unchanged(p) => format!("{agent}: {} already current", short(p)),
            Wrote::Foreign(p) => format!(
                "{agent}: left {} alone — it was not written by pstore",
                short(p)
            ),
            Wrote::Failed(why) => format!("{agent}: {why}"),
        }
    }

    /// Whether this counts as the agent now being pointed at the local model.
    pub fn wired(&self) -> bool {
        matches!(
            self,
            Wrote::Created(_) | Wrote::Updated(_) | Wrote::Unchanged(_)
        )
    }
}

fn short(p: &Path) -> String {
    p.file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| p.display().to_string())
}

/// Write `wiring`'s config into `dir`, pointing it at `serving`.
///
/// Refuses to touch a file it did not write. That is the whole safety story here: the
/// alternative is either clobbering a config someone tuned by hand, or never being able to
/// update the endpoint after a port change.
pub fn apply(wiring: &Wiring, dir: &Path, serving: &Serving) -> Wrote {
    let path = wiring.path(dir);
    let wanted = wiring.contents(serving);
    if wanted.is_empty() {
        return Wrote::Failed("pstore does not know how to configure this agent".into());
    }

    let existing = std::fs::read_to_string(&path).ok();
    match &existing {
        Some(current) if current == &wanted => return Wrote::Unchanged(path),
        Some(current) if !current.contains(STAMP) => return Wrote::Foreign(path),
        _ => {}
    }

    if let Some(parent) = path.parent()
        && let Err(e) = std::fs::create_dir_all(parent)
    {
        return Wrote::Failed(format!("creating {}: {e}", parent.display()));
    }
    match std::fs::write(&path, &wanted) {
        Ok(()) if existing.is_some() => Wrote::Updated(path),
        Ok(()) => Wrote::Created(path),
        Err(e) => Wrote::Failed(format!("writing {}: {e}", path.display())),
    }
}

/// Remove a config pstore wrote, leaving anyone else's alone.
///
/// The counterpart to [`apply`], and the reason it is worth having: a generated file that can
/// only be undone by hand is a file people stop trusting the button that made it.
pub fn revert(wiring: &Wiring, dir: &Path) -> Wrote {
    let path = wiring.path(dir);
    match std::fs::read_to_string(&path) {
        Err(_) => Wrote::Unchanged(path),
        Ok(current) if !current.contains(STAMP) => Wrote::Foreign(path),
        Ok(_) => match std::fs::remove_file(&path) {
            Ok(()) => Wrote::Updated(path),
            Err(e) => Wrote::Failed(format!("removing {}: {e}", path.display())),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models;

    fn serving() -> Serving {
        Serving {
            port: 8787,
            checkpoint: models::LLM_TERNARY.id,
            pid: 42,
        }
    }

    fn tmp(name: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("pstore-wire-{name}-{}", std::process::id()));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    /// Every generated config has to carry the endpoint, the model name the server actually
    /// advertises, and the marker that makes it safe to rewrite later.
    #[test]
    fn every_wiring_names_the_endpoint_and_the_model() {
        let s = serving();
        for w in WIRINGS {
            let text = w.contents(&s);
            assert!(!text.is_empty(), "{} produced nothing", w.agent_id);
            assert!(text.contains(&s.base_url()), "{}: no endpoint", w.agent_id);
            assert!(text.contains(&s.model_name()), "{}: no model", w.agent_id);
            assert!(text.contains(STAMP), "{}: no marker", w.agent_id);
            // Every config must carry a placeholder credential. The local server wants none,
            // but an OpenAI-typed provider with no key falls back to $OPENAI_API_KEY and the
            // agent refuses to start — which is what happened: zerostack died on
            // "No API key found" against an endpoint that authenticates nothing.
            assert!(
                text.contains(LOCAL_KEY),
                "{}: without a placeholder key the agent will not start",
                w.agent_id
            );
        }
    }

    /// The zerostack config is TOML read by another program, and TOML is order-sensitive:
    /// every top-level scalar has to precede the first table header, or the file does not
    /// parse as intended.
    #[test]
    fn the_zerostack_config_is_ordered_valid_toml() {
        let w = WIRINGS.iter().find(|w| w.agent_id == "zerostack").unwrap();
        let text = w.contents(&serving());

        let first_table = text.find('[').expect("a table header");
        for key in ["provider =", "model ="] {
            let at = text.find(key).unwrap_or_else(|| panic!("no {key}"));
            assert!(
                at < first_table,
                "{key} lands inside a table and would be read as one of its fields"
            );
        }
        // The key goes under the provider's own name, which is what the agent looks up.
        let keys = text.find("[api_keys]").expect("an api_keys table");
        assert!(text[keys..].contains("bonsai ="), "{text}");
    }

    /// The OpenCode config is JSON and is read by another program: it has to parse.
    #[test]
    fn the_opencode_config_is_valid_json() {
        let w = WIRINGS.iter().find(|w| w.agent_id == "opencode").unwrap();
        let text = w.contents(&serving());
        let v: serde_json::Value =
            serde_json::from_str(&text).unwrap_or_else(|e| panic!("{e}\n{text}"));

        let provider = &v["provider"]["bonsai"];
        assert_eq!(provider["options"]["baseURL"], serving().base_url());
        assert!(
            provider["models"]
                .as_object()
                .is_some_and(|m| m.contains_key(&serving().model_name())),
            "the served model must be listed: {text}"
        );
    }

    /// Writing, then rewriting, then leaving a stranger's file alone — the three cases that
    /// decide whether this is safe to put behind a button.
    #[test]
    fn writing_is_idempotent_and_never_clobbers_a_foreign_file() {
        let dir = tmp("apply");
        let w = WIRINGS.iter().find(|w| w.agent_id == "zerostack").unwrap();
        let s = serving();

        assert!(matches!(apply(w, &dir, &s), Wrote::Created(_)));
        assert!(w.path(&dir).exists(), "the file should be on disk");
        // Same input twice is not a rewrite.
        assert!(matches!(apply(w, &dir, &s), Wrote::Unchanged(_)));

        // A changed endpoint updates the file pstore wrote.
        let moved = Serving { port: 9999, ..s };
        assert!(matches!(apply(w, &dir, &moved), Wrote::Updated(_)));
        let text = std::fs::read_to_string(w.path(&dir)).unwrap();
        assert!(text.contains("9999"), "the endpoint should have moved");

        // Someone else's file is reported and left byte-for-byte alone.
        let mine = "model = \"something I chose myself\"\n";
        std::fs::write(w.path(&dir), mine).unwrap();
        assert!(matches!(apply(w, &dir, &s), Wrote::Foreign(_)));
        assert_eq!(std::fs::read_to_string(w.path(&dir)).unwrap(), mine);

        std::fs::remove_dir_all(&dir).ok();
    }

    /// Undo has the same rule as write: pstore's own file goes, anyone else's stays.
    #[test]
    fn reverting_removes_only_what_pstore_wrote() {
        let dir = tmp("revert");
        let w = WIRINGS.iter().find(|w| w.agent_id == "opencode").unwrap();

        // Nothing there is not a failure.
        assert!(matches!(revert(w, &dir), Wrote::Unchanged(_)));

        apply(w, &dir, &serving());
        assert!(matches!(revert(w, &dir), Wrote::Updated(_)));
        assert!(!w.path(&dir).exists(), "the generated file should be gone");

        let mine = "{\"model\": \"mine\"}\n";
        std::fs::write(w.path(&dir), mine).unwrap();
        assert!(matches!(revert(w, &dir), Wrote::Foreign(_)));
        assert_eq!(std::fs::read_to_string(w.path(&dir)).unwrap(), mine);

        std::fs::remove_dir_all(&dir).ok();
    }

    /// Every agent named here has to exist in the registry, or the button offers to configure
    /// something pstore cannot detect or launch.
    #[test]
    fn every_wiring_names_a_real_agent() {
        for w in WIRINGS {
            assert!(
                crate::agents::registry::AGENTS
                    .iter()
                    .any(|a| a.id == w.agent_id),
                "{} is not in the registry",
                w.agent_id
            );
        }
    }
}
